### ISSUE TITLE
typo in setup.py

### ISSUE THREAD

**Issue by sinchb** [kpdyer/libffx#4]
I can't install this lib because__init__.pyx doesn't exist, there is just__init__.py：

```
$$$:/tmp/libffx$ sudo python setup.py build
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    ext_modules = cythonize("FFX/__init__.pyx"),
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 758, in cythonize
    aliases=aliases)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 651, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 103, in nonempty
    raise ValueError(error_msg)
ValueError: 'FFX/__init__.pyx' doesn't match any files
```

**Comment by kpdyer** [comment]
Are you trying to use libffx with Cython?

**Comment by sinchb** [comment]
yes, I wanted to install libffx:

``` bash
python setup.py install
```

and then the exception was raised.

**Comment by kpdyer** [comment]
Sure, but this is with Cython, correct? At the moment, we don't explicitly support Cython. Have you tried it with Python?

**Comment by sinchb** [comment]
well... I think I understand.  I can use the FFX module directly without installation. And if I run the setup.py to install it, Cython is necessary?

**Comment by sinchb** [comment]
I rename `__init__.pyx` with `__init__.py` and the setup.py works well.

**Comment by kpdyer** [comment]
Sorry, I think I'm the confused one. I haven't touched this code in a while.

What you've highlighted is in fact a bug. Looks like there's some stray Cython calls that shouldn't be there. I'll sort this out soon.

Thanks!

**Comment by sinchb** [comment]
:smile:

**Comment by kpdyer** [comment]
I believe this issue is now fixed. Please confirm. Thanks!

**Comment by sinchb** [comment]
Thanks, it works now :)
