### ISSUE TITLE
Implementation differs from the paper for input with a range that exceeds 8^24

### ISSUE THREAD

**Issue by jan2000** [kpdyer/libffx#8]
While working on a PHP implementation of the FFX[radix] algorithm, I compared the output of my implementation with this implementation. I noticed that the output begin to differ if the input range exceeds 8^24. This is due to a wrong implementation of the "expansion" of the Y variable.

In the paper _Addendum to “The FFX Mode of Operation for Format-Preserving Encryption”_ it says:

```
Y ← first d + 4 bytes of (Y || AESK(Y ⊕ [1]16) || AESK(Y ⊕ [2]16) || AESK(Y ⊕ [3]16)··· )
```

However this implementation does actually:

```
Y ← first d + 4 bytes of (Y || AESK(Y ⊞ [1]16) || AESK(Y ⊞ [2]16) || AESK(Y ⊞ [3]16)··· )
```

Notice the difference between `⊕` and `⊞`. The paper states that for the scheme FFX[radix] `⊞` is block-wise addition. While it is nowhere explicitly stated in the paper that `⊕` means an `XOR` operation. However, it could be interpreted from the description of the `CBC-MACK(X)` algorithm (on page 2) as it states: `for j ← 1 to m, set Y ← AESK(Y ⊕ Xi)`.

To correct this implementation these lines:

``` python
            left = FFXInteger(bytes_to_long(Y), radix=self._radix, blocksize=32)
            right = FFXInteger(str(i), radix=10, blocksize=16)
            X = self.add(left, right)
            TMP += self._ecb.encrypt(X.to_bytes(16))
```

should be replaced with:

``` python
            I = FFXInteger(str(i), radix=10, blocksize=16).to_bytes(16)
            X = "".join(chr(ord(Yi) ^ ord(Ii)) for Yi, Ii in zip(Y, I))
            TMP += self._ecb.encrypt(X)
```

Test data:

```
radix=16 key=0x00000000000000000000000000000000 tweak=

Current implementation
input  000000000000000000000000000000000000000000000000
output ddb77d3be91a8e255fca9389a3d48da2b4476919744febea
input  0000000000000000000000000000000000000000000000000
output 1dad7e05f03706e8af695246afa40a49876c1d3e0699c5be1

Expected
input  000000000000000000000000000000000000000000000000
output ddb77d3be91a8e255fca9389a3d48da2b4476919744febea
input  0000000000000000000000000000000000000000000000000
output 1f7b9459d22b2bee17d5b5616e03241467767c9dcbc424c21 
```

**Comment by kpdyer** [comment]
Thanks so much for the detailed write up. I agree with your assessment.

A couple years ago I contacted the FFX authors about this because it's not covered by the test vectors but I never got a response. Nevertheless, it's a shame that I got it wrong!

Thank you!
