### ISSUE TITLE
this is useful; would you like to put it on PyPI?

### ISSUE THREAD

**Issue by kurtbrose** [kpdyer/libffx#9]
PyPI ffx right now is this:

https://pypi.python.org/pypi/ffx

Would you like to publish this library to PyPI?
https://packaging.python.org/distributing/#uploading-your-project-to-pypi

**Comment by kpdyer** [comment]
I'm not opposed to the idea.

Are you using libffx in a way that its presence on PyPI would make a workflow easier?

**Comment by kurtbrose** [comment]
Absolutely, so basically my workflow is something like this:

virtualenv newproject
workon newproject
pip install libffx

It is _much_ more convenient to just pip install into the virtual env
rather than git clone into site-packages

Another example, to use the library from within a jupyter notebook:
http://jupyter.org/ ;
http://jupyter.readthedocs.io/en/latest/install.html#installing-jupyter-using-anaconda-and-conda

This is very convenient in development environments I can share a web-link
with my colleagues that can encrypt/decrypt data under test keys.
They don't have to worry about getting libraries installed or what
application it is embedded into.

Again, it is possible to achieve this by git clone to the correct location,
it is just more convenient to let pip manage things.

Since you already have a valid setup.py, it should be very easy for you to
register + upload :-)

**Comment by kpdyer** [comment]
Ok, let me know if this is good enough:

https://pypi.python.org/pypi/libffx
